---
- name: Deploy metallb pool
  include_tasks: metallb.yml

- name: Deploy argocd namespace
  include_tasks: argo.yml

- name: Deploy Multus Network
  include_tasks: multus.yml




#- name: Remove tmp directory used for manifests
 # file:
  #  path: /tmp/k3s
   # state: absent
