---

- name: Deploy PureLB manifest
  include_tasks: purelb.yml

- name: Deploy argocd namespace
  include_tasks: argo.yml

- name: Deploy Multus Network
  include_tasks: multus.yml

- name: Deploy Longhorn Storage
  include_tasks: longhorn.yml




- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
