---
- name: Create manifests directory for temp configuration
  file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ groups['master'] }}"
  run_once: true


- name: Copy PureLB manifest to first master
  template:
    src: "purelb.j2"
    dest: "/tmp/k3s/purelb.yml"
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ groups['master'] }}"
  run_once: true


- name: Apply PureLB manifest
  command: >-
    k3s kubectl apply -f /tmp/k3s/purelb.yml
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5

- name: Copy PureLB CRDS to first master
  template:
    src: "purelbcrds.j2"
    dest: "/tmp/k3s/purelbcrds.yml"
    owner: "{{ ansible_user }}"
    mode: 0755
  with_items: "{{ groups['master'] }}"
  run_once: true


- name: Apply PureLB CRDS
  command: >-
    k3s kubectl apply -f /tmp/k3s/purelbcrds.yml
  register: this
  changed_when: false
  run_once: true
  until: this.rc == 0
  retries: 5
