- name: Create manifests directory on first master
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

- name: Copy flannel config directory
  template:
    src: "flannelconf.j2"
    dest: "/home/tannerru/10-flannel.conflist"
    owner: root
    group: root
    mode: 0644
 # when: ansible_hostname == hostvars[groups['master'][0]]['ansible_hostname']

