apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media
  labels:
    app: sonarr_service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8989
    protocol: TCP
    targetPort: 8989
    
  selector:    
    app: sonarr
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    dep: sonarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 4000m
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: media
              mountPath: /media

            - name: config
              mountPath: /config

      volumes:
        - name: media
          nfs:
            server: {{truenas}}
            path: {{media}}

        - name: config
          nfs:
            server: {{truenas}}
            path: /mnt/Slow/Media
