apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
  
  namespace: media
  labels:
    app: sabnzbd_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http2
    port: 8090
    protocol: TCP
    targetPort: 8090
   
  selector:    
    app: sabnzbd
  type: LoadBalancer
  loadBalancerIP: 10.0.40.165
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    dep: sabnzbd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: sabnzbd
          
          image: binhex/arch-sabnzbd
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 2000m
          ports:
          - name: port8080
            containerPort: 8080
          - name: port8090
            containerPort: 8090
        
          volumeMounts:
            - name: downloads
              mountPath: /downloads

            - name: config
              mountPath: /config

      volumes:
        - name: downloads
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Downloads

        - name: config
          persistentVolumeClaim:
             claimName: sabnzbd-config
