apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn

  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media
  labels:
    app: radarr_service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: 7878
    
  selector:    
    app: radarr
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    dep: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: media
              mountPath: /media

            - name: config
              mountPath: /config

      volumes:
        - name: media
          nfs:
            server: 10.0.40.3
            path: /mnt/Fast/TempMedia/

        - name: config
          persistentVolumeClaim:
            claimName: "radarr-config"
