apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseer-service
  
  namespace: media
  labels:
    app: jellyseer_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 5055
    protocol: TCP
    targetPort: 5055
    
  selector:    
    app: jellyseer
  type: LoadBalancer
  loadBalancerIP: 10.0.40.163
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: media
  labels:
    dep: jellyseer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: jellyseer
          
          image: fallenbagel/jellyseerr:develop
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 2000m
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config

      volumes:
        - name: config
          persistentVolumeClaim:
             claimName: jellyseer-config
