apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media
  labels:
    app: radarr_service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: 7878
    
  selector:    
    app: radarr
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    dep: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 4000m
          ports:
            - containerPort: 7878
 
