apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  
  namespace: media
  labels:
    app: radarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: 7878
    
  selector:    
    app: radarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.162
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    dep: radarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: radarr
          
          image: linuxserver/radarr
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 2000m
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: media
              mountPath: /media

            - name: config
              mountPath: /config

      volumes:
        - name: media
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Media

        - name: config
          persistentVolumeClaim:
             claimName: radarr-config
